<a href="https://colab.research.google.com/github/kllana/--201-0-01-/blob/main/hw/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [15]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [17]:
np.full((7),7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [18]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [19]:
arr = np.random.rand(10)
print (arr)
arr2 = arr [::-1]
print (arr2)

[0.77387955 0.87329211 0.45176406 0.08703125 0.7582959  0.54566662
 0.26108527 0.16505233 0.05037298 0.55113351]
[0.55113351 0.05037298 0.16505233 0.26108527 0.54566662 0.7582959
 0.08703125 0.45176406 0.87329211 0.77387955]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [21]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [22]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [23]:
np.tile(np.arange(0, 5), (5, 1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [24]:
arr = np.random.rand(10, 10)
means = np.mean(arr, axis=1)
result = arr - means
print(result)

[[ 0.3911123   0.40668492 -0.55632422  0.39992982 -0.1646261  -0.46380656
  -0.24481104 -0.51612741  0.37213638 -0.05192562]
 [-0.39027634 -0.43173676 -0.16887958  0.00542507 -0.32783082  0.20442762
  -0.26312317  0.38932507  0.41276429  0.28852487]
 [ 0.0407302   0.50568082 -0.22303565  0.53532084  0.03866128  0.03787309
  -0.1283378   0.25634374 -0.03904069  0.09113843]
 [-0.32455605 -0.11310251  0.06533424 -0.22633388 -0.12500111 -0.49595073
  -0.2974967  -0.47076715  0.01828409  0.44056099]
 [-0.06525679  0.46855661 -0.21445829 -0.2691635  -0.03529707 -0.24713234
   0.00548725  0.3871882  -0.05308605  0.23870711]
 [-0.1683781   0.49014249  0.39979397  0.31490791 -0.18550622 -0.27841295
   0.49638423  0.12749557 -0.36562294  0.19019331]
 [ 0.53361206  0.09955244 -0.2166962   0.27401373 -0.36509934  0.30762039
   0.24551864 -0.4486712  -0.25231093 -0.41417868]
 [ 0.14163436 -0.26113069  0.1605698   0.29555451  0.20745743  0.00504931
   0.49628422 -0.19245605 -0.20249417  0.13774959]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [25]:
arr = np.random.rand(10, 10)
means = np.mean(arr, axis=0)
result = arr - means
print(result)

[[-3.80199631e-01  3.12461329e-01  7.03833318e-02 -2.99722486e-01
  -3.96158242e-01 -2.78756910e-01 -5.30790253e-01 -1.40498346e-01
   1.93592042e-01 -2.25199268e-01]
 [-2.18546189e-01 -2.62082591e-01  9.61035574e-02  8.92001272e-03
   3.44270696e-01 -4.15688179e-01 -2.62549633e-01  3.56813742e-01
   2.72096806e-01  2.35462971e-01]
 [ 1.86619719e-01 -2.37651525e-01 -3.70989332e-01 -1.99064464e-03
   4.48957063e-02  3.66856526e-02 -1.06671376e-01 -1.56479472e-01
   2.72995211e-01  2.97115224e-01]
 [ 2.96830956e-01 -2.44260931e-01  1.34033195e-02  2.88701549e-01
   2.00238391e-01  4.25079819e-01  8.59168434e-02 -6.56797552e-02
   7.31030978e-02  1.39953860e-01]
 [ 1.92695279e-01  3.73798106e-01  4.64553310e-01  3.23176707e-01
  -2.25733638e-01  1.15583761e-01 -1.14809945e-01  4.39741619e-01
  -2.09705837e-02 -4.42992214e-01]
 [-3.66214511e-01 -3.63878789e-04  2.69101584e-01 -1.43574352e-01
   7.76853153e-02 -4.66941240e-01  3.80258867e-01 -2.76036826e-01
  -2.00849080e-01 -3.66301565e-01

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [26]:
arr = np.random.rand(5, 5)
maxim = np.max(arr, axis=1)
minim = np.min(arr, axis=1)
result = np.column_stack((arr, maxim, minim))
print(result)

[[0.1229625  0.69959562 0.14536767 0.8711479  0.80541908 0.8711479
  0.1229625 ]
 [0.79121967 0.75418298 0.54135694 0.75779499 0.35286454 0.79121967
  0.35286454]
 [0.13634746 0.16138579 0.4903471  0.15161182 0.33355073 0.4903471
  0.13634746]
 [0.34169827 0.91214795 0.16393871 0.17837234 0.47049187 0.91214795
  0.16393871]
 [0.40927149 0.24842079 0.67010802 0.74836904 0.06786281 0.74836904
  0.06786281]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [27]:
odds = np.arange(1, 51, 2).reshape(5, 5)
evens = np.arange(0, 50, 2).reshape(5, 5)
product = np.dot(odds, evens)
print(np.linalg.det(product))
#обратной матрицы не существует
print (product)


1.5046327690525217e-32
[[ 700  750  800  850  900]
 [1700 1850 2000 2150 2300]
 [2700 2950 3200 3450 3700]
 [3700 4050 4400 4750 5100]
 [4700 5150 5600 6050 6500]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [28]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
