<a href="https://colab.research.google.com/github/kllana/--201-0-01-/blob/main/hw/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((7),7)

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 101, 2)

5) Создать массив случайных чисел и развернуть его задом наперёд

In [17]:
arr = np.random.rand(10)
print (arr)
arr2 = arr [::-1]
print (arr2)

array([0.32168756, 0.49943459, 0.47279413, 0.58142586, 0.51082734,
       0.88522492, 0.39506133, 0.75691339, 0.35227861, 0.63431856])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [3]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [16]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [14]:
np.tile(np.arange(0, 5), (5, 1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [28]:
arr = np.random.rand(10, 10)
means = np.mean(arr, axis=1)
result = arr - means
print(result)

[[-0.48396728  0.31717338  0.19226476  0.24631895  0.2588183   0.29907873
  -0.23538491  0.25861357 -0.08620512  0.28626032]
 [ 0.17227741 -0.22998136  0.06283476  0.27026155 -0.57411742  0.22652181
   0.01357241  0.16302213  0.04858143 -0.23015935]
 [-0.1733078  -0.41467443  0.10986667 -0.13076601 -0.58020842 -0.14559781
   0.08153649  0.33433399 -0.14337316  0.3765786 ]
 [-0.43690541  0.34829039  0.28745781  0.20644208 -0.29015667 -0.38044896
  -0.43239822  0.35010201  0.02270852  0.10362171]
 [-0.43023123  0.28031664  0.43766136  0.28401926  0.27971897  0.40645341
   0.36139865  0.32471143 -0.59547517 -0.07229633]
 [-0.29950818 -0.10234559  0.35484864 -0.0222492   0.08604599 -0.2357432
  -0.47579864 -0.08489861 -0.37881454  0.21963242]
 [-0.59352662 -0.03303506  0.40373328 -0.26489062  0.18226306  0.48620844
  -0.03857294  0.35615918  0.33130367 -0.20819129]
 [ 0.02517035  0.02294844 -0.3591556   0.34669821 -0.48708364 -0.22240365
   0.19611432  0.33560175  0.13478146  0.37309473]
 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [29]:
arr = np.random.rand(10, 10)
means = np.mean(arr, axis=0)
result = arr - means
print(result)

[[-0.35340667  0.00281318 -0.51063263  0.42845177  0.54470516 -0.08078927
  -0.22615741  0.18470266  0.29104105 -0.04056281]
 [ 0.08901001 -0.42582531 -0.36858393  0.23141047 -0.1355788   0.54267306
  -0.32907504 -0.16024022 -0.47620796 -0.26070327]
 [-0.32238848 -0.26973681  0.11577688 -0.1181194   0.18322791 -0.363262
  -0.34968739 -0.42613005 -0.39620656 -0.11470159]
 [-0.26449231 -0.25653558  0.17536724  0.21134819 -0.3721195   0.33250447
   0.05251251 -0.21839235 -0.21724053  0.28168855]
 [ 0.46836916 -0.37588161  0.06783953 -0.3148188   0.07582857 -0.15357645
  -0.08617589  0.35431527  0.22130012 -0.301595  ]
 [-0.12487911  0.44220362  0.33596484  0.07367084 -0.41805192  0.12714588
  -0.19134936 -0.2633493   0.31621808  0.09074532]
 [ 0.4088424   0.31196905 -0.1064787  -0.39926214  0.37570924  0.34859781
   0.4455235   0.18822402  0.07656791 -0.26225485]
 [-0.25420303  0.38275876 -0.13954601  0.41413588  0.16184325 -0.36421517
   0.36184634  0.11801565  0.19976481  0.11998743]
 [

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.rand(5, 5)
maxim = np.max(arr, axis=1)
minim = np.min(arr, axis=1)
result = np.column_stack((arr, maxim, minim))
print(result)

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [33]:
odds = np.arange(1, 51, 2).reshape(5, 5)
evens = np.arange(0, 50, 2).reshape(5, 5)
product = np.dot(odds, evens)
inverse = np.linalg.inv(product)
print (product)
print(inverse)


[[ 700  750  800  850  900]
 [1700 1850 2000 2150 2300]
 [2700 2950 3200 3450 3700]
 [3700 4050 4400 4750 5100]
 [4700 5150 5600 6050 6500]]
[[ 8.24633721e+11  0.00000000e+00 -2.19902326e+12  1.09951163e+12
   2.74877907e+11]
 [ 2.93750000e-02 -2.19902326e+12  3.29853488e+12 -0.00000000e+00
  -1.09951163e+12]
 [-2.74877907e+12  4.39804651e+12 -0.00000000e+00 -2.19902326e+12
   5.49755814e+11]
 [ 2.19902326e+12 -2.19902326e+12 -1.09951163e+12 -0.00000000e+00
   1.09951163e+12]
 [-2.74877907e+11  0.00000000e+00  0.00000000e+00  1.09951163e+12
  -8.24633721e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [40]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
